name: publish-pydoctor-apidocs
on:
- push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .
        python -m pip install pydoctor

    - name: Generate pydoctor documentation
      run: |
        # Allow pydoctor to exit with non-zero status code (for now)
        set +e

        # Run pydoctor build
        pydoctor \
            --project-name=python-igraph \
            --project-url=https://github.com/$GITHUB_REPOSITORY \
            --html-viewsource-base=https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
            --make-html \
            --html-output=./apidocs \
            --project-base-dir="$(pwd)" \
            --docformat=restructuredtext \
            --introspect-c-modules \
            --intersphinx=https://docs.python.org/3/objects.inv \
            ./igraph ./src/_igraph

    - name: Publish pydoctor documentation to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate pydoctor documentation"
